criticalmanufacturing/cli

cmf-cli/Handlers/PackageType/HtmlPackageTypeHandler.cs
cmf-cli/cmf.csproj
docs/cmf/Cmf_Common_Cli_Commands.md
docs/cmf/Cmf_Common_Cli_Objects.md
docs/cmf/Cmf_Common_Cli_Utilities.md
npm/package-lock.json
npm/package.json

Include default step deploy bundles for HTML

---

.commitlintrc.json
.husky/commit-msg
.husky/pre-commit
.versionrc.json
package-lock.json
package.json

This PR will prevent broken commits and standardize our commit messages. This is helpful for readability and also when generating a Change Log. This uses:
- pre-commit hook: runs tests
- commit-msg hook: check if the commit message is valid according to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [husky](https://typicode.github.io/husky/) to install and run the git hooks (just run `npm run prepare` in the project root)
- [standard-version](https://github.com/conventional-changelog/standard-version) to generate the Change Log

refactor: commit checks

---

cmf-cli/Builders/JSONValidatorCommand.cs
cmf-cli/Builders/ProcessCommand.cs
cmf-cli/Commands/build/BuildCommand.cs
cmf-cli/Handlers/PackageType/DataPackageTypeHandler.cs
cmf-cli/Handlers/PackageType/IoTPackageTypeHandler.cs
cmf-cli/Handlers/PackageType/PackageTypeHandler.cs
docs/cmf/Cmf_Common_Cli_Builders.md
docs/cmf/Cmf_Common_Cli_Commands.md
docs/cmf/Cmf_Common_Cli_Handlers.md
docs/cmf/cmf.xml
tests/Objects/CmfMockJsonData.cs
tests/Specs/Validators.cs

New Builder for validation JSONs
- Currently applies to packages of type Data

Development 30 add json validator builder

---

cmf-cli/resources/template_feed/helpSrcPkg/.gitignore
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/c_analytics/_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/c_analytics_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/configurations.md
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/deeactions/_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/deeactions_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/entitytypes/_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/entitytypes_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/exportedobjects/_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/exportedobjects_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/generictables/_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/generictables_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/html/cconverters/_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/html/cconverters_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/html/components/_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/html/components_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/html/datasources/_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/html/datasources_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/html_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/lookuptables.md
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/namegenerators/_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/namegenerators_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/services/_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/services_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/smarttables/_template
cmf-cli/resources/template_feed/helpSrcPkg/Help.Src.Package/assets/techspec/artifacts/smarttables_template

chore: add Help Missing artifacts

---

cmf-cli/Commands/init/InitCommand.cs
cmf-cli/Constants/CliConstants.cs
cmf-cli/resources/template_feed/init/.template.config/template.json
cmf-cli/resources/template_feed/init/Builds/CI-Package.yml
cmf-cli/resources/template_feed/init/Builds/CI-Publish.yml
cmf-cli/resources/template_feed/init/Builds/CI-Release.yml
cmf-cli/resources/template_feed/init/Builds/PR-Package.yml
cmf-cli/resources/template_feed/init/EnvironmentConfigs/GlobalVariables.yml

update pipeline templates

---

cmf-cli/resources/template_feed/init/EnvironmentConfigs/GlobalVariables.yml

development use cli v2

---

cmf-cli/resources/template_feed/iot/IoT.Package/IoTData/cmfpackage.json
tests/Specs/New.cs

closes #122 
- Template Resources had incorrect nomenclature for IoT Data, Automaton Workflow Files
- For IoTData, Workflow Files location was changed to root level
- For IoTData, Masterdata was changed to be under Masterdata Folder

Development 122 fix template iot data

---

cmf-cli/Builders/ConsistencyCheckCommand.cs
cmf-cli/Commands/BaseCommand.cs
cmf-cli/Commands/assemble/AssembleCommand.cs
cmf-cli/Commands/list/ListDependenciesCommand.cs
cmf-cli/Handlers/PackageType/PackageTypeHandler.cs
cmf-cli/Logger.cs
cmf-cli/Objects/CmfPackage.cs
cmf-cli/Program.cs
cmf-cli/Utilities/GenericUtilities.cs
cmf-cli/cmf.csproj
npm/run.js
package-lock.json
package.json
tests/Specs/ListDependencies.cs
tests/Specs/Logging.cs
tests/tests.csproj

This pull request replaces our basic Console output implementation with a Spectre Console based implementation. This PR:
- adds log level support (env var and runtime switch)
- hides debug messages by default (which can be displayed with the log level support)
- replaces our custom tree from `ls` with an ANSI compatible implementation
- fixes the flakiness with the progress indicator
- replaces our custom status progress indicator with an ANSI compatible implementation
- this gracefully degrades as well if the terminal does not support ANSI
- AnsiConsole makes testing of console interactions possible and easy (check the logging tests)
- fixes a couple of bugs found during testing

Logging Enhancements

---

cmf-cli/Handlers/PackageType/DataPackageTypeHandler.cs
cmf-cli/Handlers/PackageType/DataPackageTypeHandlerV2.cs
cmf-cli/Handlers/PackageType/ExportedObjectsPackageTypeHandler.cs
cmf-cli/Handlers/PackageType/HelpPackageTypeHandler.cs
cmf-cli/Handlers/PackageType/HtmlPackageTypeHandler.cs
cmf-cli/Handlers/PackageType/IoTDataPackageTypeHandler.cs
cmf-cli/Handlers/PackageType/IoTPackageTypeHandler.cs
cmf-cli/Handlers/PackageType/PackageTypeHandler.cs
cmf-cli/Handlers/PackageType/RootPackageTypeHandler.cs
cmf-cli/Objects/CmfPackage.cs
cmf-cli/resources/templateFiles/manifest.xml

closes #127
- Add Cli Package Type to DF Manifest Xml 
This is important for the local plugin to know what is the context of the manifest

feat: add cliPackage as tag in the manifest xml

---

cmf-cli/Commands/init/InitCommand.cs
tests/Specs/New.cs

fix(init): enforce mandatory options

---

cmf-cli/Commands/new/HTMLCommand.cs
cmf-cli/Utilities/FileSystemUtilities.cs
tests/Specs/New.cs

fix(new HTML): set webapp as compilable, necessary for bundle generation

---

cmf-cli/Handlers/PackageType/PresentationPackageTypeHandler.cs
cmf-cli/resources/template_feed/html/HTML.Package/cmfpackage.json
tests/Objects/MockPackage.cs
tests/Specs/Pack.cs

- fix(pack): support packing presentation packages without any UI package
- fix(pack): support relative LBO paths for feature packages

support presentation packages without ui packages

---

.github/workflows/npm-publish.yml
.github/workflows/pr-tests.yml
cmf-cli/cmf.csproj
core/core.csproj
npm/package-lock.json
npm/package.json
tests/tests.csproj

This PR migrates our runtime/SDK to .NET 6.

migrate to .NET 6

---

cmf-cli/Builders/CmdCommand.cs
cmf-cli/Builders/DotnetCommand.cs
cmf-cli/Builders/GitCommand.cs
cmf-cli/Builders/GulpCommand.cs
cmf-cli/Builders/NPMCommand.cs
cmf-cli/Builders/NPXCommand.cs
cmf-cli/Builders/ProcessCommand.cs
cmf-cli/Builders/SingleStepCommand.cs
cmf-cli/Handlers/PackageType/GenericPackageTypeHandler.cs
core/Objects/CmfPackage.cs
core/Objects/ProcessBuildStep.cs
tests/Specs/Build.cs

feat(build): support manifest build steps for generic packages

---

cmf-cli/Commands/TemplateCommand.cs

fix(init): add support for MES runtime environments

---

cmf-cli/cmf.csproj
cmf-cli/resources/template_feed/init/Builds/CD-Containers.yml
cmf-cli/resources/template_feed/init/EnvironmentConfigs/GlobalVariables.yml
core/Utilities/FileSystemUtilities.cs
core/core.csproj
npm/package-lock.json
npm/package.json
tests/Specs/Pack.cs

- fix(pack): fix(pack): ensure zip paths always use forward slash
- fix(pipelines): change trigger format issue
- chore(pipelines): target CLI v3
- chore: bump to 3.0.0-6

Zip path forward slash enforce

---

src/scaffolding/pipeline_import.md
src/scaffolding/pipelines.md

- fixup! docs: provide an overview of our pipeline design

documentation pipeline docs

---

cmf-cli/Handlers/PackageType/PackageTypeHandler.cs
cmf-cli/resources/template_feed/init/NuGet.Config

This PR increases the compatibility with different NuGet feeds for the .NET solutions in the project structure

Remove protocol version from main NuGet source

---

cmf-cli/Handlers/PackageType/IoTPackageTypeHandler.cs
tests/Specs/Pack.cs

Unlike expected, DF doesn't skip unknown deployment steps, instead complaining of an unknown handler. This PR gates the inclusion of these steps to MES versions which DF is known to support these steps.

fix(pack): gate new IoT steps to DF versions that actually support them

---

cmf-cli/Handlers/PackageType/PresentationPackageTypeHandler.cs
cmf-cli/resources/templateFiles/IoT/config.json
testenvironments.json
tests/Specs/Pack.cs

fix: iot package changing html config.json with wrong version

---

cmf-cli/Handlers/PackageType/DataPackageTypeHandlerV2.cs

deprecate lbo generation

---

cmf-cli/Handlers/PackageType/DataPackageTypeHandlerV2.cs
cmf-cli/Handlers/PackageType/PackageTypeHandler.cs
cmf-cli/Interfaces/IPackageTypeHandler.cs
tests/Specs/Build.cs

build dotnet projects on data package build

---

.github/workflows/npm-publish.yml
cmf-cli/Commands/plugin/PluginsCommand.cs
cmf-cli/Program.cs
core/Attributes/CmfCommandAttribute.cs
core/Commands/BaseCommand.cs
core/Objects/NPMClient.cs
tests/Mocks/MockNPMClient.cs
tests/Specs/CmfPackage_Load.cs
tests/Specs/ListDependencies.cs
tests/Specs/Plugins.cs
tests/Specs/Startup.cs

feat: add command for plugin discovery

---

npm/package-lock.json
npm/package.json
npm/run.js
package-lock.json
package.json

chore: update npm dependencies 
fix: use the LOCALAPPDATA env var to check for global execution

fix: use the LOCALAPPDATA env var to check for global execution

---

cmf-cli/cmf.csproj
cmf-cli/resources/template_feed/init/Builds/.tasks/clean-agent-directories.yml
cmf-cli/resources/template_feed/init/Builds/.tasks/install-cli.yml
cmf-cli/resources/template_feed/init/Builds/.tasks/install-cmf-pipeline.yml
cmf-cli/resources/template_feed/init/Builds/.tasks/use-dotnet-version.yml
cmf-cli/resources/template_feed/init/Builds/.tasks/use-node-version.yml
cmf-cli/resources/template_feed/init/Builds/CI-Changes.yml
cmf-cli/resources/template_feed/init/Builds/CI-Package.yml
cmf-cli/resources/template_feed/init/Builds/PR-Changes.yml
cmf-cli/resources/template_feed/init/Builds/PR-Package.yml
cmf-cli/resources/template_feed/init/EnvironmentConfigs/GlobalVariables.yml
core/core.csproj
npm/package-lock.json
npm/package.json

- migration pr and ci pipelines inline powershell to cmf-pipeline commands
- refactor re-used steps into templates
- change behaviour to support multiple packages in one single pipeline run
- this will reduce the AzureDevOps build agents usage

feat(pipelines): refactor pr and ci pipelines

---

cmf-cli/resources/template_feed/init/Builds/CI-Changes.yml
cmf-cli/resources/template_feed/init/Builds/PR-Changes.yml
cmf-cli/resources/template_feed/init/Builds/PR-Package.yml

replaces PR #263:
- instead of using powershell, use `cmf-pipeline` plugin to handle this

search for test cases on pullrequest workitems

---

CHANGES.md
cmf-cli/cmf.csproj
core/Logger.cs
core/core.csproj
npm/package-lock.json
npm/package.json

Enhancements for plugin development

Release 3.4.2

---

tests/Specs/Assemble.cs
tests/Specs/Pack.cs

test: increase test coverage for pack and assemble

---

cmf-cli/Builders/ProcessCommand.cs
cmf-cli/Handlers/PackageType/HtmlNgCliPackageTypeHandler.cs
cmf-cli/resources/templateFiles/HTML/config.ng.json
core/Enums/StepType.cs

- chore: fix typo
- chore: replace values with tokens in index.html, ngsw.json and assets/config.json

development ui deployment transforms

---

cmf-cli.sln
cmf-cli/Commands/build/IoTLibCommand.cs
cmf-cli/Commands/new/IoTCommand.cs
cmf-cli/Handlers/PackageType/PackageTypeHandler.cs
cmf-cli/Handlers/PackageType/SecurityPortalPackageTypeHandler.cs
core/Objects/CmfPackage.cs
core/Objects/ExecutionContext.cs
core/Objects/RelatedPackage.cs
core/Objects/RelatedPackageCollection.cs
core/Utilities/FileSystemUtilities.cs
testenvironments.json
tests/Specs/Build.cs
tests/Specs/Pack.cs
tests/Utilities/TestUtilities.cs

- chore: reduce log messages verbosity set some log messages to debug
- chore(refactor): improve RelatedPackages logic

refactor relatedpackages logic

---

cmf-cli/Commands/init/InitCommand.cs
cmf-cli/cmf.csproj
core/core.csproj
npm/package-lock.json
npm/package.json
tests/Specs/Init.cs

workaround for issue dotnet/command-line-api#1879

fix(init): workaround for System.CommandLine bug that considers unknown option as argument values

---

CHANGES.md
cmf-cli/Commands/init/InitCommand.cs
cmf-cli/Handlers/PackageType/PresentationPackageTypeHandler.cs
cmf-cli/cmf.csproj
core/Commands/TemplateCommand.cs
core/core.csproj
npm/package-lock.json
npm/package.json

- chore: remove ISOLocation validation as an infra parameter
- refactor: improve error handling running templates
- fix(iot): transform step only makes sense for MES <v10
- chore: bump to 4.0.2-0
- chore: release 4.0.2

Release 4.0.2

---

cmf-cli/Commands/new/IoTCommand.cs
tests/Specs/New.cs

New IoTPackage should build and pack after building and packaging itself not before (pre)

Development Fix New IoT Command Related Package Change Action Order

---

cmf-cli/Commands/new/HTMLCommand.cs
cmf-cli/resources/template_feed/help/from1000/Help.Package/package.json

This PR introduce cross-env dependency and script in package.json to open help/html page on specific port, prevent memory leaks.

feat(help/html): Cross-env, port and prevent memory leak

---

cmf-cli/Commands/new/IoTCommand.cs
cmf-cli/Handlers/PackageType/IoTPackageTypeHandler.cs
cmf-cli/resources/template_feed/iot/from1000/IoT.Package/%iotpackages%/.dev-tasks.json
cmf-cli/resources/template_feed/iot/from1000/IoT.Package/%iotpackages%/cmfpackage.json
cmf-cli/resources/template_feed/iot/from1000/IoT.Package/%iotpackages%/gulpfile.js

In the new iot, we were only supporting custom tasks. With this change we now support custom drivers.

Development iot support for drivers

---

cmf-cli/Handlers/PackageType/IoTPackageTypeHandler.cs

Skip Gulp steps if scaffold does not include gulp and its gulpfile

Fix IoT build gulp steps for older scaffolds

---

cmf-cli/Builders/ExecuteCommand.cs
cmf-cli/Builders/IBuildCommand.cs
cmf-cli/Builders/IProcessCommand.cs
cmf-cli/Builders/JSONValidatorCommand.cs
cmf-cli/Builders/NPMCommand.cs
cmf-cli/Builders/NgBuildFileTokenReplacerCommand.cs
cmf-cli/Builders/ProcessCommand.cs
cmf-cli/Commands/build/IoTLibCommand.cs
cmf-cli/Handlers/PackageType/IoTDataPackageTypeHandlerV2.cs
cmf-cli/Handlers/PackageType/IoTPackageTypeHandler.cs
cmf-cli/resources/template_feed/iot/from1000/IoT.Package/%iotpackages%/cmfpackage.json
core/Commands/BaseCommand.cs
core/Commands/IBaseCommand.cs
core/Objects/ExecutionContext.cs
core/Objects/IProcessStartInfoCLI.cs
core/Objects/ProcessStartInfoCLI.cs
core/StartupModule.cs
tests/Mocks/MockBuildCommand.cs
tests/Specs/New.cs
tests/Specs/TestBuildCommand.cs

feat: add support for iot drivers

---

cmf-cli/Commands/new/IoTCommand.cs

fix(new-iot): yoeman version

---

cmf-cli/Builders/NgBuildFileTokenReplacerCommand.cs

Added the 'urlSuffix' property to the 'lboGenerator' configuration in the HTML config.json file.

chore(html): replace token for urlSuffix associated with lboGenerator

---

cmf-cli/resources/template_feed/init/.project-config.json
cmf-cli/resources/template_feed/init/.template.config/template.json
core/Commands/TemplateCommand.cs
tests/Fixtures/init/config_no_AD.json
tests/Specs/Init.cs

fix(init): make default domain optional, environment may not have AD config

---

cmf-cli/Builders/DEEValidatorCommand.cs
tests/Specs/DEEValidator.cs

- **fix(DEE validation): support alternate tags used by DEE Debugger**
- **refactor(DEE validation): display all errors instead of exiting on first**

DEE validator: support alternate tags

---

cmf-cli/Commands/new/GrafanaCommand.cs
cmf-cli/Factories/PackageTypeFactory.cs
cmf-cli/Handlers/PackageType/GrafanaPackageTypeHandler.cs
cmf-cli/resources/template_feed/grafana/.template.config/template.json
cmf-cli/resources/template_feed/grafana/Grafana.Package/%version%/dashboards/dashboards.yaml
cmf-cli/resources/template_feed/grafana/Grafana.Package/%version%/datasources/datasources.yaml
cmf-cli/resources/template_feed/grafana/Grafana.Package/README.md
cmf-cli/resources/template_feed/grafana/Grafana.Package/cmfpackage.json
core/Enums/PackageType.cs
tests/Objects/MockPackage.cs
tests/Specs/New.cs
tests/Specs/Pack.cs

Adds new command for Grafana custom package creation

feat(new): grafana custom package

---

cmf-cli/Handlers/PackageType/HelpNgCliPackageTypeHandler.cs
cmf-cli/resources/template_feed/help/from1000/Help.Package/package.json

feat(help): run generate of documents database and markdown links

---

cmf-cli/resources/template_feed/help/from1100/Help.Package/tsconfig.json

Add skipLibCheck to true on the Cmf.Custom.Help tsconfig.json template.

chore(templates): add skipLibCheck to true for Cmf.Custom.Help

---

cmf-cli/Commands/LayerTemplateCommand.cs
cmf-cli/Commands/new/IoTCommand.cs
cmf-cli/Handlers/PackageType/IoTPackageTypeHandler.cs
cmf-cli/resources/template_feed/iot/from1000/atl/.template.config/template.json
cmf-cli/resources/template_feed/iot/from1000/atl/IoT.Package/%iotpackages%/package.json

feat(nodePackageBundler): iot package

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

development devcontainer

---

docs/src/02-learn/tutorials/1-scaffolding/1-project-init/index.md
docs/src/03-explore/guides/iot-scaffolding.md

A new branch with a single commit. With the fixes for PR #491

docs: fix iot scaffolding docs for v10 onwards if using task library

---

core/Interfaces/IRepositoryAuthStore.cs
core/Objects/CIFSClient.cs
core/Objects/ExecutionContext.cs
core/Objects/NPMClient.cs
core/Repository/CIFSRepositoryClient.cs
core/Repository/Credentials/CIFSRepositoryCredentials.cs
core/Repository/Credentials/DockerRepositoryCredentials.cs
core/Repository/Credentials/IRepositoryCredentials.cs
core/Repository/Credentials/NPMRepositoryCredentials.cs
core/Repository/Credentials/NuGetRepositoryCredentials.cs
core/Repository/Credentials/PortalRepositoryCredentials.cs
core/Repository/NPMRepositoryClient.cs
core/Services/RepositoryAuthStore.cs
core/StartupModule.cs
core/Utilities/GenericUtilities.cs
tests/Mocks/MockEnvironment.cs
tests/Specs/CIFSClient.cs
tests/Specs/NPM.cs
tests/Specs/New.cs
tests/Specs/Pack.cs
tests/Specs/Plugins.cs
tests/Specs/Repositories.cs
tests/Specs/RepositoryCredentials.cs
tests/Specs/Startup.cs

Authenticate repositories against credentials file

---

tests/Specs/Repositories.cs

test: add unit test to ensure our conversion from zip to tgz keeps the deployment steps on the package.json file

test: add unit test to ensure our conversion from zip to tgz keeps the deployment steps on the package.json file

---

core/Repository/Credentials/DockerRepositoryCredentials.cs

The commands `cmf login` and `cmf login sync` would fail if run in systems without docker installed (because we use the `docker` command to sync credentials). this PR makes it emit only a warning in such cases.
Also, although these changes seem very specific to Windows (with Win32 references) the behavior is consistent on linux as well, with the same error codes.

fix: login sync cmd succeed even if docker is not installed

---

cmf-cli/Commands/new/HTMLCommand.cs

This pull request fixes the arguments used by the cmf cli when creating an HTML project.

fix(html): fix ng add arguments

---

cmf-cli/Commands/publish/PublishCommand.cs
tests/Specs/Publish.cs

We have the repository URLs inside the `repositories.json` file. However, when it comes to the `cmf publish` command, it did not integrate with this file at all, instead requiring the user to always type out the URL explicitly. Furthermore, it also had a bug because the `--repository` flag was not marked as required, and so if no repository was provided, it simply threw a `NullReferenceException`, which is not ideal from a UX perspective.
This PR adds some additional validations and more user friendly error messages when no repositories are passed, but it also adds two new helper flags: `--ci` and `--release`, that allow the user to avoid having to type the full URL every time.
- `cmf publish --ci <packageFile>` will publish the package to the Continuous Integration repository, saved …

feat: add shortcut flags to publish to the CI and Release repositories

---

cmf-cli/resources/template_feed/init/app_deployment_manifest.xml

This PR updates the app deployment manifest to correct a few minor issues.

fix(init): update app deployment manifest

---

cmf-cli/Commands/new/IoTCommand.cs

556 cmf new iot command

---

cmf-cli/cmf.csproj
core/Enums/StepType.cs
core/core.csproj
npm/package-lock.json
npm/package.json

add update configuration step type, used on iot repository packages

feat: add UpdateConfiguration to StepType
