cmf-cli/Constants/CliConstants.cs, cmf-cli/Handlers/PackageType/PresentationPackageTypeHandler.cs, cmf-cli/cmf.csproj, docs/cmf/Cmf_Common_Cli_Constants.md, docs/cmf/cmf.xml, npm/package-lock.json, npm/package.json
For IoT Packages we should ignore the driver packages.
This was tested and validated
=> Ignore driver packages on IoT Packages pack

cmf-cli/Commands/list/ListDependencies.cs, cmf-cli/Enums/PackageLocation.cs, cmf-cli/Logger.cs, cmf-cli/Objects/CmfPackage.cs, cmf-cli/Objects/Dependency.cs
The purpose of this feature is two-fold: to provide a command to list the package tree (like npm ls) and also to provide a data structure to build this tree before we execute actions on the packages, such as pack, separating the "read" phase from the pack phase, which would make this both more testable and easier to debug.
=> List Package Dependencies

cmf-cli/Commands/BaseCommand.cs, cmf-cli/Commands/plugin/PluginCommand.cs
Improvements to CLI plugins discovery and execution:
- Avoid loading plugin **cmf-.exe** (or other valid extension), that would result in a command named **""**
- On the extraction of the command name from the executable name, do not replace "cmf-" and the extension everywhere, this may lead to a wrong command name
- On a plugin execution, parameters were not correctly quoted/handled if they contained spaces
=> Improvements to plugins loading

cmf-cli/Commands/BaseCommand.cs, cmf-cli/Commands/bump/BumpCommandIoTConfiguration.cs, cmf-cli/Commands/bump/BumpCommandIoTCustomization.cs, cmf-cli/Commands/list/ListDependenciesCommand.cs, cmf-cli/Commands/pack/PackCommand.cs, cmf-cli/Commands/publish/PublishCommand.cs
replace getDefault with parseArgument in command arguments/options of type IDirectoryInfo, as the default casts do not work with IDirectoryInfo (closes #16)
=> replace getDefault with parseArgument in command arguments/options

.github/workflows/npm-publish.yml, PUBLISHING.MD, package.json
For development, sometimes it is useful to publish a test version to npm for use in pipelines or other automation scenarios.
We currently have the @next tag, but this is exclusively for development versions with unstable but commited features.
This PR allows:
- running the publish workflow manually
- will publish to npm with the tag equal to the branch name
- this limits us to one version published per branch, which should be more than enough for any testing
- @latest and @next will still be published by releasing and pre-releasing, respectively
=> Allow publishing test versions

cmf-cli/Commands/new/BusinessCommand.cs, cmf-cli/resources/template_feed/init/Builds/CI-Changes.json, cmf-cli/resources/template_feed/init/Builds/CI-Package.json, cmf-cli/resources/template_feed/init/Builds/Environment-BackupRestore.json, cmf-cli/resources/template_feed/init/Builds/PR-Changes.json, cmf-cli/resources/template_feed/init/Builds/PR-Changes.yml, cmf-cli/resources/template_feed/init/Builds/PR-Package.json
Repository paths in some places were using some internal nomenclature instead of the Repository `init` input.
We also now make sure PR-Changes invoke PR-Package only if enabled and in the same folder (this was unlikely to cause conflicts nowadays as we had with CI-Package during a migration, but the behaviour should be the same in both places for consistency)
=> fix(pipelines): make repository paths consistent

cmf-cli/Handlers/PackageType/PackageTypeHandler.cs, cmf-cli/Objects/CmfPackage.cs, cmf-cli/Utilities/ExtensionMethods.cs, cmf-cli/resources/template_feed/init/Builds/CI-Release.yml, docs/cmf/Cmf_Common_Cli_Utilities.md, docs/cmf/cmf.xml, tests/Specs/ListDependencies.cs, tests/Specs/Restore.cs
=> Restore Command tests

cmf-cli/Commands/local/LocalCommand.cs, docs/cmf/Cmf_Common_Cli_Attributes.md, docs/cmf/Cmf_Common_Cli_Commands.md, docs/cmf/Cmf_Common_Cli_Constants.md, docs/cmf/Cmf_Common_Cli_Handlers.md, docs/cmf/Cmf_Common_Cli_Objects.md, docs/cmf/Cmf_Common_Cli_Utilities.md, docs/cmf/cmf.xml
The local command group contains commands only useful to CMF employees, as they depend on our internal infrastructure. These commands will be migrated to a plugin in the near future, but to prevent confusion we should remove it from the help, at least.
=> Hide 'local' command group from help

cmf-cli/Utilities/GenericUtilities.cs
fixes #135 
Consistency Check should only regard local packages, right now it's validating both remote and local packages
=> Development 135 consistency check only local pkg

cmf-cli/Objects/ExecutionContext.cs, cmf-cli/Objects/NPMClient.cs, cmf-cli/Objects/VersionService.cs, cmf-cli/Program.cs, cmf-cli/cmf.csproj, npm/package-lock.json, npm/package.json, tests/Specs/Logging.cs, tests/Specs/Startup.cs
This PR addresses #94 
To help with decoupling and testing, we're using the dotnet default IoC container to register a few singletons. This could replace most of the properties of the ExecutionContext.
If we prefer to use Hosting, we may remove the ExecutionContext altogether, this is something we can look into.
=> feat: add version checks at start up refactor: add an IoC Container for easily mocking services

tests/Objects/AssertWithMessage.cs, tests/Specs/Assemble.cs, tests/Specs/CmfPackage_Load.cs, tests/Specs/CmfPackage_Save.cs, tests/Specs/ConsistencyCheckValidator.cs, tests/Specs/JsonValidator.cs, tests/Specs/ListDependencies.cs, tests/Specs/Logging.cs, tests/Specs/New.cs, tests/Specs/Pack.cs, tests/Specs/Restore.cs, tests/Specs/Startup.cs, tests/tests.csproj
Migrate our test solution to xUnit. Due to our ExecutionContext implementation, we are disabling
parallel testing to be reviewed later
=> test: migrate tests to xUnit

cmf-cli/Handlers/PackageType/PackageTypeHandler.cs, tests/Objects/MockPackage.cs, tests/Specs/Pack.cs
check if there was any content packed only if the package manifest contains contentToPack entries
test(pack): add test cases for contentToPack variations
=> fix(pack): additional contentToPack check

cmf-cli/Handlers/PackageType/HtmlPackageTypeHandler.cs
Dev-tasks were updated to support brotli compression when building in production mode. This PR adds brotli to the cmf cli build command.
=> Add brotli compression

cmf-cli/resources/template_feed/init/Builds/CD-Containers.yml, cmf-cli/resources/template_feed/init/Builds/CI-Release.yml, cmf-cli/resources/template_feed/init/EnvironmentConfigs/%EnvironmentName%.yml
add support in CI-Release and CD-Containers to allow to define the package to be installed by environment.
example:
- environment A
- PackageABC
- environment B
- PackageDEF
=> feat(pipelines): support package installation by environment

core/Utilities/GenericUtilities.cs
`cmf ls` is printing the parent package instead of the current level package when printing the dependency tree. The dependency tree itself is correct, only the printed tree is wrong.
=> fix(ls): correct printed tree found package labels

cmf-cli/Commands/LayerTemplateCommand.cs, cmf-cli/Commands/assemble/AssembleCommand.cs, cmf-cli/Commands/build/BuildCommand.cs, cmf-cli/Commands/bump/BumpCommand.cs, cmf-cli/Commands/bump/BumpIoTConfigurationCommand.cs, cmf-cli/Commands/bump/BumpIoTCustomizationCommand.cs, cmf-cli/Commands/init/InitCommand.cs, cmf-cli/Commands/list/ListDependenciesCommand.cs, cmf-cli/Commands/local/GenerateLBOsCommand.cs, cmf-cli/Commands/local/GetLocalEnvironmentCommand.cs, cmf-cli/Commands/pack/PackCommand.cs, cmf-cli/Commands/restore/RestoreCommand.cs, cmf-cli/Program.cs, cmf-cli/resources/template_feed/init/Builds/CI-Package.yml, core/Objects/CmfPackage.cs, core/Objects/ExecutionContext.cs, core/Objects/TelemetryService.cs, core/Utilities/GenericUtilities.cs, core/core.csproj, tests/Mocks/MockNPMClient.cs, tests/Mocks/MockTelemetryService.cs, tests/Mocks/MockVersionService.cs, tests/Specs/Startup.cs, tests/Specs/Telemetry.cs
This PR contains opt-in telemetry for CLI and CLI plugins. There are two levels: basic and extended telemetry.
Basic telemetry currently only tracks the CLI startup and logs:
- CLI name and version
- latest version available in NPM
- if the CLI version is stable or testing
- if the CLI is outdated
**no identifiable information is collected in basic telemetry**
However, any user can optionally enable extended telemetry, which might help with troubleshooting. **Extended telemetry includes identifiable information** and as such should be used with care. This includes the basic telemetry, plus:
- for the version (startup) log, it also includes
- current working directory
- hostname
- IP
- username
It also tracks and logs the package tree if, for any command, the tree must be computed. This …
=> CLI telemetry

cmf-cli/Commands/assemble/AssembleCommand.cs
=> fix: assemble throws object reference not set when dependency doesn't exist in repository

cmf-cli/Commands/TemplateCommand.cs, cmf-cli/Commands/init/InitCommand.cs, cmf-cli/Constants/CliConstants.cs, cmf-cli/resources/template_feed/init/.template.config/template.json, cmf-cli/resources/template_feed/init/Builds/CD-Containers.json, cmf-cli/resources/template_feed/init/Builds/CI-Changes.json, cmf-cli/resources/template_feed/init/Builds/CI-Package.json, cmf-cli/resources/template_feed/init/Builds/CI-Publish.json, cmf-cli/resources/template_feed/init/Builds/CI-Release.json, cmf-cli/resources/template_feed/init/Builds/Environment-BackupRestore.json, cmf-cli/resources/template_feed/init/Builds/PR-Changes.json, cmf-cli/resources/template_feed/init/Builds/PR-Package.json, cmf-cli/resources/template_feed/init/Builds/policies-development.json, cmf-cli/resources/template_feed/init/Builds/policies-master.json, tests/Specs/New.cs
As a convention, we assumed the repository url is the same as the project name. However, for
multi-repo projects this may not be true. As such, if the repository url is a valid Azure DevOps
repository, we can and should extract the repository name from there.
fixes #160
=> fix(init): derive repository name from valid repository url

cmf-cli/Handlers/PackageType/IoTPackageTypeHandler.cs, core/Enums/StepType.cs
This PR adds the steps DeployRepositoryFiles and GenerateRepositoryIndex to allow the envmanager to deploy the runtime packages and update the index.
These are the resulting steps:
```xml
<steps>
<step type="DeployFiles" contentPath="runtimePackages/**" />
<step type="DeployFiles" contentPath="*.ps1" />
<step type="DeployFiles" contentPath="*.bat" />
<step type="Generic" onExecute="$(Package[Cmf.FEC.IoT.Packages].TargetDirectory)/runtimePackages/ValidateIoTInstall.ps1" />
<step type="Generic" onExecute="$(Package[Cmf.FEC.IoT.Packages].TargetDirectory)/runtimePackages/PublishToRepository.ps1" />
<step type="Generic" onExecute="$(Package[Cmf.FEC.IoT.Packages].TargetDirectory)/runtimePackages/PublishToDirectory.ps1" />
<step type="DeployRepositoryFiles" contentPath="runtimePackages/**" /> …
```
=> feat(): Add ConnectIoT deployment steps to IoT Package

cmf-cli/Commands/init/InitCommand.cs, cmf-cli/resources/template_feed/init/.template.config/template.json, cmf-cli/resources/template_feed/init/Builds/CD-Containers.json, cmf-cli/resources/template_feed/init/Builds/CD-Containers.yml, cmf-cli/resources/template_feed/init/Builds/CI-Changes.json, cmf-cli/resources/template_feed/init/Builds/CI-Changes.yml, cmf-cli/resources/template_feed/init/Builds/CI-Package.json, cmf-cli/resources/template_feed/init/Builds/CI-Publish.json, cmf-cli/resources/template_feed/init/Builds/CI-Release.json, cmf-cli/resources/template_feed/init/Builds/PR-Changes.json, cmf-cli/resources/template_feed/init/Builds/PR-Changes.yml, cmf-cli/resources/template_feed/init/Builds/PR-Package.json, tests/Specs/New.cs
Provides an extra option to `init`, `--pipelinesFolder`, which will create all pipelines inside the folder specified by the option value. If not specified, `init` will create all pipelines in the root, as at present.
- fix: change CD-Containers: had an hardcoded agent pool
- feat(init): allow namespacing the pipelines for multi-site projects
=> Allow namespacing pipelines

CHANGES.md, cmf-cli/Handlers/PackageType/DataPackageTypeHandlerV2.cs, cmf-cli/Handlers/PackageType/PackageTypeHandler.cs, cmf-cli/Handlers/PackageType/PresentationPackageTypeHandler.cs, cmf-cli/Interfaces/IPackageTypeHandler.cs, cmf-cli/cmf.csproj, cmf-cli/resources/templateFiles/IoT/config.json, core/Objects/ProcessBuildStep.cs, core/core.csproj, npm/package-lock.json, npm/package.json, testenvironments.json, tests/Specs/Build.cs, tests/Specs/CmfPackage_Save.cs, tests/Specs/Pack.cs
- fix: iot package changing html config.json with wrong version fixes #202
- chore: add testenvironments.json file to support debug on wsl
- chore: remove LBOGeneration from default steps closes #213
- fix: serialization changing workingDirectory>buildSteps fixes #190
- chore: move optional parameter to interface class
- fix: build dotnet projects on data package build
- test(build): add data package build closes #66
- chore: bump to 3.1.2-0
- chore: release 3.1.2
=> Release 3.1.2

cmf-cli/Handlers/PackageType/PackageTypeHandler.cs, cmf-cli/Handlers/PackageType/PresentationPackageTypeHandler.cs, tests/Specs/Bump.cs
when the bump command run in a package with the type Presentation (currently: Help, HTML or IoT), the version inside of the *metadata.ts will be also updated.
in TypeScript " or ' are valid string delimiters, and cli was only expecting ".
this PR adds the support for both scenarios, " and '.
=> fix(bump): support single and double quotes on metadata ts file

cmf-cli/resources/template_feed/init/Builds/CI-Release.yml, cmf-cli/resources/template_feed/init/Builds/Environment-BackupRestore.yml
in Azure DevOps Server 2020 Update 1.2, the extract task has changed behaviour and now does not deep match, requiring more complete paths to do the extractions
=> fix(builds): fixed issues caused by azuredevops update

cmf-cli/Program.cs, core/Objects/NPMClient.cs, core/Objects/TelemetryService.cs, tests/Specs/Startup.cs
refactor: make telemetry service parameterized to be used in plugins 
chore: make startup warning state which app they relate to
=> refactor: make telemetry service parameterized to be used in plugins chore: make startup warning state which app they relate to

cmf-cli/cmf.csproj, core/core.csproj, npm/package-lock.json, npm/package.json
global-dirs 3.0.1 breaks execution if we are using node version managers. It assumes $APPDATA
pm is
the default prefix, which is not the case when managers are used.
=> fix: downgrade global-dirs to 3.0.0

cmf-cli/Builders/JSONValidatorCommand.cs, cmf-cli/Commands/LayerTemplateCommand.cs, cmf-cli/Commands/UILayerTemplateCommand.cs, cmf-cli/Commands/assemble/AssembleCommand.cs, cmf-cli/Commands/bump/BumpIoTCustomizationCommand.cs, cmf-cli/Commands/new/DataCommand.cs, cmf-cli/Commands/new/FeatureCommand.cs, cmf-cli/Commands/new/HTMLCommand.cs, cmf-cli/Commands/new/HelpCommand.cs, cmf-cli/Handlers/PackageType/PackageTypeHandler.cs, cmf-cli/Program.cs, core/Enums/ErrorCode.cs, core/LoggerHelpers.cs, core/Objects/CmfPackage.cs, core/Utilities/CliException.cs, core/Utilities/ExtensionMethods.cs, tests/Specs/Logging.cs
- allow ErrorCodes on CliException
- replace all `Log.Error return` and `throw new Exception` with `throw new CliException`
- add method to handle exception when comes from Reflection `exception is TargetInvocationException`
=> better error handling #33

cmf-cli/Factories/PackageTypeFactory.cs, cmf-cli/Handlers/PackageType/GenericPackageTypeHandler.cs, cmf-cli/Handlers/PackageType/PackageTypeHandler.cs, core/CoreMessages.Designer.cs, core/CoreMessages.resx, core/Enums/PackageType.cs, core/Enums/StepType.cs, core/Objects/CmfPackage.cs, core/Objects/Step.cs, tests/Objects/MockPackage.cs, tests/Specs/PackageTypeHandler.cs
feat(restore dependencies): CoreBiz - move CopyLibs to cmf-cli restore dependencies
chore(restore): Added dependenciesDirectory property to allow to choose path where to extract package dependencies
chore(bug fix): fixed bug in which cli package with Generic type with no build steps would throw error when running cmf pack
chore(bug fix): fixed bug when trying to cmf pack to path '.' it would include cmfpackage.json, so it was added to default exceptions
chore: bump to 3.4.1-0
=> Add DependenciesDirectory property to cmfpackage.json

core/StartupModule.cs
We have scenarios where the cli is running on (as example) AzureDevOps pipelines.
In that scenario, the `AnsiConsole.Profile.Out.IsTerminal` returns `false`, and the `AnsiConsole.Profile.Width` defaults to 80, which is a low value and causes unexpected break lines.
An issue is already open on spectreconsole repo:
https://github.com/spectreconsole/spectre.console/issues/216
=> chore(log): double out width if not running on terminal

src/scaffolding/external.md
Remove internal scripts from external documentation file in favor of relevant commands
Internal scripts and documentation associated with them will be moved to `COMMON`
=> docs: remove internal scripts from external docs

cmf-cli/Program.cs
BREAKING CHANGE: -- is no longer needed/supported: all params are sent to plugin
This could use a refactor to use System.CommandLine more, but we're waiting for the customizable invocation pipeline they are planning to ship.
=> refactor(plugins)!: bypass System.CommandLine API when invoking plugins

cmf-cli/Commands/build/business/BusinessCommand.cs, cmf-cli/Commands/build/business/ValidateStartAndEndMethodsCommand.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/Abstractions/IValidateLogger.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/Abstractions/Processors/IBaseProcessor.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/Abstractions/Processors/IOrchestrationEndMethodProcessor.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/Abstractions/Processors/IOrchestrationStartMethodProcessor.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/Abstractions/Processors/IProcessorFactory.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/Enums/ClassType.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/ErrorMessages.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/Extensions/ChildSyntaxListExtensions.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/Extensions/ClassDeclarationSyntaxExtensions.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/Extensions/ListExtensions.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/Extensions/ServiceCollectionExtensions.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/Extensions/StringExtensions.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/Extensions/SyntaxNodeExtensions.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/Processors/BaseProcessor.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/Processors/OrchestrationEndMethodProcessor.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/Processors/OrchestrationStartMethodProcessor.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/Processors/ProcessorFactory.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/SolutionLoader.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/SolutionValidator.cs, cmf-cli/Commands/build/business/ValidateStartEndMethods/ValidateLogger.cs, cmf-cli/cmf.csproj, tests/Specs/Build.cs, tests/Specs/ValidateStartAndEndMethods.cs, tests/tests.csproj
Added a new command: cmf build business validateStartAndEndMethods <solutionPath> <listOfFiles>
The objective of this development was to validate start and end methods in services and orchestration but I've already added a "structure" to later implement validation for entity types also.
Note: If no list of files is provided the command validates all files in the solution.
=> Development 84981 start end method validator

cmf-cli/Commands/build/html/HtmlCommand.cs, cmf-cli/Commands/build/html/LinkLBOsCommand.cs, cmf-cli/Handlers/PackageType/HtmlNgCliPackageTypeHandler.cs
This PR adds a new command, `cmf build html linkLBOs`, which will allow using custom LBOs when compiling UI packages. The LBO location is fixed ($/Libs/LBOs/TypeScript) and will be automatically linked to a UI package if the LBOs exist.
=> feat(LBOs): automatically link LBOs when building UI packages

docs/src/scaffolding/Traditional/index.md
- docs: remove repositoryUrl from up to MES v9 scaffolding
- docs: remove repositoryUrl from up to MES v9 scaffolding
=> development docs fix scaffolding 9x

cmf-cli/Handlers/PackageType/GenericPackageTypeHandler.cs, tests/Specs/Build.cs
This PR fixes the `build` command when used on a `Generic` package type without `BuildSteps`
Run: `cmf build`
with the following cmfpackage.json:
```json
{
"packageId": "Cmf.Custom.SecurityPortal",
"version": "1.0.0",
"description": "This package deploys Cmf.Custom.SecurityPortal in Critical Manufacturing MES",
"packageType": "Generic",
"isInstallable": true,
"targetLayer": "securityportal",
"isUniqueInstall": true,
"steps": [
{
"order": 1,
"type": "TransformFile",
"file": "config.json",
"tagFile": true
}
],
"dependencies": [],
"contentToPack": [
{
"source": "config.json",
"target": "."
}
]
}
```
```sh
Caught exception at program.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
System.NullReferenceException: Object reference not set …
```
=> fix(build): check generic type build steps

cmf-cli/Handlers/PackageType/HtmlNgCliPackageTypeHandler.cs
This PR fixes the `build` command when used on `HTML` package on v10.1.1
After analyses, I noticed that after linking LBO's we still need to get the packages the LBOs depend on.
With this PR, it will install and build the LBO package as well before linking. 
Run: `cmf build` on `HTML` package with v.10.1.1
```sh
Executing 'ng build Cmf.Custom.HTML'
- Generating browser application bundles (phase: setup)...
√ Browser application bundle generation complete.
√ Browser application bundle generation complete.
../Libs/LBOs/TypeScript/esm/cmf-lbos.mjs:1:0-28 - Error: Module not found: Error: Can't resolve 'moment' in 
'C:\agentsWork\SRV-PI-BS01-11\9451\s\Libs\LBOs\TypeScript\esm'
Error: ../Libs/LBOs/TypeScript/index.d.ts:1:20 - error TS2307: Cannot find module 'moment' or its corresponding type …
```
=> fix(build): install and build lbos package

cmf-cli/Commands/build/html/LinkLBOsCommand.cs, cmf-cli/Handlers/PackageType/HelpNgCliPackageTypeHandler.cs, cmf-cli/Handlers/PackageType/HtmlNgCliPackageTypeHandler.cs, core/Utilities/ExtensionMethods.cs, package.json
- fix(build html): move install and build LBOs to link LBOs command
- fix(build html/help): fixed token injection for HTML and Help packages
- chore(publish): use another repository for dev releases
=> Support building HTML without custom LBOs. Fix token support in Help packages.

cmf-cli/Handlers/PackageType/PackageTypeHandler.cs, tests/Specs/PackageTypeHandler.cs
It was reported that on linux, the order of contentToPack was alphanumeric.
I wasn't able to reproduce this issue, anyway I think this can solve the issue.
=> fix: force order by name on getContentToPack method

cmf-cli/Handlers/PackageType/RootPackageTypeHandler.cs, tests/Specs/Pack.cs
Fixes `cmfapp.json not found!` issue when packing a feature inside an app repository type
=> fix(Pack): use cmfapp.json from project root when it doesn't exist locally

cmf-cli/Handlers/PackageType/DataPackageTypeHandlerV2.cs, tests/Specs/Pack.cs
This PR fixes an issue causing the target platform of the first master data package in the cmfpackage.json to be copied to all other master data package entries. Modified test Data_MasterData to account for this scenario.
=> Fixed manifest generation for packages with multiple master data packages targeting different platforms

cmf-cli/Commands/init/InitCommand.cs, cmf-cli/resources/template_feed/init/.project-config.json, cmf-cli/resources/template_feed/init/.template.config/template.json, core/Objects/ProjectConfig/ProjectConfigV1.cs, tests/Specs/Init.cs
This PR adds a new flag to allow adding an app configuration to the App project.
It also fixes an existing issue where the App Icon path is incorrectly configured.
=> feat(init): Add App environment configuration

cmf-cli/Handlers/PackageType/BusinessPackageTypeHandler.cs, cmf-cli/Handlers/PackageType/TestPackageTypeHandler.cs, tests/Specs/Bump.cs
Added logic to run bump from package folder for business and test packages to prevent changing wrong assembly info files.
#433
=> fix(bump): prevent wrong assembly files from being changed when running bump from root

cmf-cli/Builders/JSONValidatorCommand.cs, tests/Specs/JsonValidator.cs
- Add support in the json validator to validate Automation Workflows Subworkflow relation
=> feat(json validator): validate subworkflows closes #452

npm/package.json, npm/postinstall.js
The request to download the portal-sdk binary, through `axios`, is not working. It **may** be related with this [issue](https://github.com/axios/axios/issues/4533).
1. Check for proxy (through env vars, thanks to `proxy-from-env`) and build the appropriate `httpAgent` and `httpsAgent`.
2. Send the `httpAgent` and `httpsAgent` to the `axios` `GET` request.
3. Bumped `axios` dependency to `^1.7.9`.
4. Included `proxy-agent@^5.0.0`.
Check this portal-sdk's [pull-request](https://github.com/criticalmanufacturing/portal-sdk/pull/96) for more information and the test of `npm i`.
=> fix(): post install's artifact fetch not working behind a proxy

cmf-cli/Commands/new/IoTCommand.cs, tests/Specs/New.cs
The `--isAngularPackage` flag type was incorrectly marked as string, which was making it so that it was never recognized as true.
Furthermore, there was a bug in the logic of version comparison (missing parentheses were causing, even with the `--isAngularPackage` flag set to true, on MES versions 10.2.7/8, the generation to happen for ATL packages instead of Angular ones. This part of the code was refactored to make it more readable.
The test cases were updated to cover both the cases where the flag is explicitly passed or not, and for both versions prior and subsequent to 10.2.7. Additionally, a check was added to make sure angular package was indeed being generated (thought the presence of the file `angular.json`). All tests are passing now:
Fixes #470.
=> fix(new iot): angular package generation flag for MES >= 10.2.7

cmf-cli/Commands/build/html/ExtractI18nCommand.cs, cmf-cli/Commands/build/html/LocalizeCommand.cs, core/Objects/CmfPackage.cs
This PR adds 2 commands to support the solution described in the loop to support GUI localization in custumization projects.
The first command is named `extract-i18n`:
* It calls the `ng extract-i18n` command which will generate a `.xlf` file containing all the localized messages (product + project)
* It has a simple post-processing step which removes the product messages. The goal is to have a file containing only messages from the project so that it is easier to have it in version control.
* The project is then expected to maintain their own translation files, also in `.xlf` format.
The second command is named `localize`:
* It calls the `ng extract-i18n` command again, which will generate a `json` file containing all the localized messages (product + project)
* Then, it calls the …
=> feat: Support GUI localization in customization projects

cmf-cli/Commands/publish/PublishCommand.cs, core/Objects/CIFSClient.cs, core/Repository/CIFSRepositoryClient.cs, core/Repository/Credentials/CIFSRepositoryCredentials.cs, tests/Specs/CIFSClient.cs, tests/Specs/Publish.cs
Can now publish package to a CIFS share.
Added tests to CIFSClient and also to assert publish command parses repository input correctly as an absolute Uri.
=> Implement put method on CIFSRepositoryClient

cmf-cli/Commands/publish/PublishCommand.cs, core/Interfaces/IRepositoryClient.cs, core/Objects/CIFSClient.cs, core/Repository/CIFSRepositoryClient.cs
List method was removed from IRepositoryClient interface.
Publish command was changed to accommodate new changes.
**Extra:**
Added checks to guarantee a valid connection is active when executing actions on a CIFSClient.
=> chore: remove List method from IRepositoryClient

cmf-cli/Commands/init/InitCommand.cs, cmf-cli/resources/template_feed/init/.devcontainer/devcontainer.json, cmf-cli/resources/template_feed/init/.template.config/template.json, tests/Specs/Init.cs
When scaffolding a new project with `cmf init`, we want to include the default devcontainer definition. 
Since the devcontainer image is only available for MES v10 and above, we omit the generation of the file for any MES versions below that.
The devcontainer installs two separate features, one of them to install this this cli inside the container. We always pass the version of the cli to install inside the devcontainer, to match by default, the version of the cli that was used to scaffold the project. However, the version of the cli is also relevant when using CI/CD pipelines. Special care should be taken to make sure that the version of the cli the pipeline uses, and the version of the cli used by the devcontainer match.
=> feat: add devcontainer definition to init template

cmf-cli/Commands/login/SyncCommand.cs, cmf-cli/resources/template_feed/init/.devcontainer/devcontainer.json, core/Interfaces/IRepositoryAuthStore.cs, core/Repository/Credentials/IPortalRepositoryCredentials.cs, core/Repository/Credentials/PortalRepositoryCredentials.cs, core/Services/RepositoryAuthStore.cs, tests/Specs/Login.cs, tests/Specs/RepositoryCredentials.cs
Developed in sequence of #515, depends on that before merging this one.
The goal here, still in line with using our devcontainer image to develop MES customization projects, is to always run the following command when launching the devcontainer: `cmf login sync`
This command previously only synced the credentials stored inside `~/.cmf-auth.json` to the various tools (nuget, npm, docker, etc..) inside the devcontainer. However, there were two situations where the user would have to manually run `cmf login` before launching the devcontainer:
- The very first time, since no credentials were stored yet
- When the CM Portal token expired (usually after 30 days of the last login)
With this change, every time `sync` runs, the existence of the token (and also its expiration date) are …
=> feat: login sync renew portal token

cmf-cli/Commands/login/LoginCommand.cs, cmf-cli/resources/template_feed/init/.devcontainer/devcontainer.json, core/Repository/Credentials/NuGetRepositoryCredentials.cs, docs/src/03-explore/commands/login.md, docs/src/03-explore/commands/login_sync.md, tests/Specs/RepositoryCredentials.cs
We were running the command `cmf login sync` on the `"postStartCommand"`. This did not work however, because the `$BROWSER` environment variable is not yet defined at that stage (the reason being that the variable is defined by VS Code, while the `"postStartCommand"` and similar commands are managed by the `devcontainer` tooling before VS Code takes over).
See https://github.com/microsoft/vscode-remote-release/issues/9935
One of the solutions suggested there was to define a task instead, that is defined with:
```
"runOptions": {
"runOn": "folderOpen"
},
```
Tested this and it works like this.
=> fix: devcontainer able to run cmf login sync at launch

cmf-cli/Handlers/PackageType/TestPackageTypeHandler.cs
For some reason, the `cmf build` for test packages is forcing the `dotnet restore` to run only with the `NuGet.config` file on the root of the project.
https://github.com/criticalmanufacturing/cli/blob/1277020adcc2c7b489f6bedbee5f938c8b0e5647/cmf-cli/Handlers/PackageType/TestPackageTypeHandler.cs#L52-L59
This behavior is different from the one for building the business packages, for example:
https://github.com/criticalmanufacturing/cli/blob/9739fd13d5b7f2b79d1ee03943b9225137fa3f3e/cmf-cli/Handlers/PackageType/BusinessPackageTypeHandler.cs#L57-L63
This is a problem because it prevents the `dotnet restore` command from resolving the **user-level config files** located in places like the home directory, and which are sometimes needed because they may contain credentials to private NuGet …
=> fix: cmf build of test pkgs ignoring user-level nuget configs

cmf-cli/Commands/publish/PublishCommand.cs, cmf-cli/Handlers/PackageType/TestPackageTypeHandler.cs, cmf-cli/resources/templateFiles/Tests/package.json, core/Services/CmfPackageController.cs, tests/Specs/Pack.cs, tests/Specs/Publish.cs
Now that MES will support grabbing packages Deployment Framework from NPM feeds, and the CLI is able to publish Deplyment Framework packages into NPM feeds, we had one problem: test packages are "special" in that they are not Deployment Framework packages (they do not have a manifest file, and they are not installed into an MES system).
Nevertheless, for consistency and to keep the architecture of things simple, we want to be able to publish these packages to NPM as well. For that, the purpose of this PR is to, when packaging a test package, generate a `package.json` file into the resulting archive, so that it can be uploaded to NPM via a regular `cmf pusblish` command execution.
=> feat: pack tests generates a package.json to allow publishing to NPM

cmf-cli/Commands/new/HTMLCommand.cs
This PR updates the ng serve arguments to include serve path and update index.html to have the correct name and baseHref.
=> feat(html): modify index.html and ng serve arguments for apps

cmf-cli/Commands/assemble/AssembleCommand.cs
This PR modifies the assemble command to generate a package containing the app files.
One of these files is the app icon, which is important when installing an app.
This package was already generated when running the "pack" command but was not generated by the "assemble" command.
=> fix: modified assemble command to add the app icon

core/Enums/StepType.cs, core/Objects/NPMClient.cs, core/Repository/NPMRepositoryClient.cs, core/Services/CmfPackageController.cs
When trying to publish clickhouse types, the CLI did not support all the needed step types:
After adding the missing step types, a new issue popped up when reading the `*.tgz` files. This was strange because these `*.tgz` files were created by the CLI itself, based on the `*.zip` files downloaded from the envmanager. It seems like the issue was using `SharpCompress.Writers.Tar.TarWriter` to create the files, but then using `System.Formats.Tar.TarReader` to read them.
The issue seems to have been fixed in https://github.com/dotnet/runtime/pull/101172, which by the looks of it, has not been backported to .NET 8. So instead, I rewrote the code using `SharpCompress.Readers.Tar.TarReader`.
There are still a lot of places that use `System.Formats.Tar.TarReader`. In an ideal world, I think we …
=> fix: publishing clickhouse backup packages

cmf-cli/Commands/assemble/AssembleCommand.cs, cmf-cli/Commands/new/BusinessCommand.cs, cmf-cli/Commands/new/HTMLCommand.cs, cmf-cli/Constants/CliConstants.cs, cmf-cli/Handlers/PackageType/RootPackageTypeHandler.cs, cmf-cli/resources/template_feed/business/from900/.template.config/template.json, cmf-cli/resources/template_feed/business/from900/Business.Package/ApplicationVersion/Version.csproj, cmf-cli/resources/template_feed/business/from900/Business.Package/Business.sln, core/Objects/ExecutionContext.cs, core/Utilities/FileSystemUtilities.cs, tests/Fixtures/app/cmfapp.json, tests/Specs/New.cs, tests/Specs/Pack.cs
This pull request updates the application version `.csproj` template to be correctly included in the resulting solution and also to include the correct licensed application name instead of the tenant name. This change affects only Business packages created in a repository of type App.
Side changes:
- A AppData property was created in the ExecutionContext to avoid repeated code across the codebase
- Unit Tests were updated to include cmfapp.json file
=> fix(business): fix application version csproj template to include licensed app name

core/Repository/Credentials/PortalRepositoryCredentials.cs, core/Services/RepositoryAuthStore.cs, tests/Specs/RepositoryCredentials.cs
When we run `cmf login` or `cmf login sync`, we are automatically authenticating against the CM's Customer Portal, and also on all official CM repositories (Docker, NPM, NuGet, etc....).
The way this is implemented, since the credentials for all repositories are the same as the credentials for the Customer Portal, is by storing on the `.cmf-auth.json` file only the portal credentials.
The repository credentials are then derived from these in real time. We had a bug however, that we were not deriving them in memory when they were needed to be used by the internal NPM client used by the CLI to download packages, etc...
=> fix: load derived credentials for internal repo operations

core/Services/CmfPackageController.cs
I found a bug when converting `.zip` packages created with, for example, Windows Explorer, to `.tgz`. If the `.zip` has any folders inside, like so:
Our code is creating the folders as files, resulting in invalid `.tgz` archives.
Although this issue **does not happen when packages are generated with our `cmf pack`** (the way packages are supposed to be generated), this change makes package conversion more resilient and avoids potential future issues.
=> fix: skip folder entries when converting zip to tgz
